# Generated by Django 3.2.11 on 2022-09-21 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(editable=False, help_text='Ingredient ID', primary_key=True, serialize=False)),
                ('korean', models.CharField(help_text='Product Brand', max_length=3024)),
                ('oldKorean', models.CharField(help_text='Product Brand', max_length=3024, null=True)),
                ('english', models.CharField(help_text='Product Brand', max_length=3024, null=True)),
                ('oldEnglish', models.CharField(help_text='Product Brand', max_length=3024, null=True)),
                ('hazardScoreMin', models.CharField(help_text='Product Brand', max_length=2, null=True)),
                ('hazardScoreMax', models.CharField(help_text='Product Brand', max_length=2, null=True)),
                ('dataAvailability', models.CharField(help_text='Product Brand', max_length=20, null=True)),
                ('allergy', models.CharField(help_text='Product Brand', max_length=1, null=True)),
                ('twenty', models.CharField(help_text='Product Brand', max_length=255, null=True)),
                ('twentyDetail', models.CharField(help_text='Product Brand', max_length=255, null=True)),
                ('goodForOily', models.BooleanField(default=False)),
                ('goodForSensitive', models.BooleanField(default=False)),
                ('goodForDry', models.BooleanField(default=False)),
                ('badForOily', models.BooleanField(default=False)),
                ('badForSensitive', models.BooleanField(default=False)),
                ('badForDry', models.BooleanField(default=False)),
                ('skinRemarkG', models.CharField(help_text='Product Brand', max_length=50, null=True)),
                ('skinRemarkB', models.CharField(help_text='Product Brand', max_length=50, null=True)),
                ('Cosmedical', models.CharField(help_text='Product Brand', max_length=50, null=True)),
                ('purpose', models.CharField(help_text='Product Brand', max_length=512, null=True)),
                ('limitation', models.CharField(help_text='Product Brand', max_length=512, null=True)),
                ('forbidden', models.CharField(help_text='Product Brand', max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(help_text='Product ID', primary_key=True, serialize=False)),
                ('brand', models.CharField(help_text='Product Brand', max_length=255)),
                ('name', models.CharField(help_text='Product Name', max_length=255)),
                ('subName', models.CharField(help_text='Product Name', max_length=255)),
                ('barcode', models.CharField(help_text='Product Barcode', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLargeCategory',
            fields=[
                ('id', models.AutoField(help_text='Product Large Type ID', primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='Product Large Type Name', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductMediumCategory',
            fields=[
                ('id', models.AutoField(help_text='Product Medium Type ID', primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='Product Medium Type Name', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSmallCategory',
            fields=[
                ('id', models.AutoField(help_text='Product Small Type ID', primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='Product Small Type Name', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.AutoField(help_text='SubProduct ID', primary_key=True, serialize=False)),
                ('subName', models.CharField(help_text='Product Name', max_length=255)),
                ('barcode', models.CharField(help_text='Product Barcode', max_length=13)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.product')),
            ],
        ),
        migrations.CreateModel(
            name='SPIRelation',
            fields=[
                ('id', models.AutoField(help_text='Product Ingredients mapping table', primary_key=True, serialize=False)),
                ('ingredients_id', models.ForeignKey(db_column='ingredients_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.ingredients')),
                ('subproduct_id', models.ForeignKey(db_column='subproduct_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.subproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SPCRelation',
            fields=[
                ('id', models.AutoField(help_text='Product Ingredients mapping table', primary_key=True, serialize=False)),
                ('large_id', models.ForeignKey(db_column='large_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.productlargecategory')),
                ('medium_id', models.ForeignKey(db_column='medium_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.productmediumcategory')),
                ('small_id', models.ForeignKey(db_column='small_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.productsmallcategory')),
                ('subproduct_id', models.ForeignKey(db_column='subproduct_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.subproduct')),
            ],
        ),
        migrations.CreateModel(
            name='PIRelation',
            fields=[
                ('id', models.AutoField(help_text='Product Ingredients mapping table', primary_key=True, serialize=False)),
                ('ingredients_id', models.ForeignKey(db_column='ingredients_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.ingredients')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.product')),
            ],
        ),
        migrations.CreateModel(
            name='PCRelation',
            fields=[
                ('id', models.AutoField(help_text='Product Ingredients mapping table', primary_key=True, serialize=False)),
                ('large_id', models.ForeignKey(db_column='large_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.productlargecategory')),
                ('medium_id', models.ForeignKey(db_column='medium_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.productmediumcategory')),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.product')),
                ('small_id', models.ForeignKey(db_column='small_id', on_delete=django.db.models.deletion.CASCADE, to='atomom.productsmallcategory')),
            ],
        ),
    ]
