# Generated by Django 3.2.11 on 2022-10-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atomom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(help_text='Product ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product Name', max_length=255)),
                ('ocrtime', models.CharField(help_text='ocr time', max_length=255)),
                ('totaltime', models.CharField(help_text='total time', max_length=255)),
                ('requesttime', models.CharField(help_text='request time', max_length=255)),
                ('useragent', models.CharField(help_text='user-agent', max_length=255)),
            ],
        ),
    ]
